version: "3.7"

services:
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        restart: always

    mongo_account:
        image: mongo:latest
        ports:
            - "27018:27017"
        restart: always

    auth:
        image: sayid/auth:latest
        ports:
            - "4020:2000"
        restart: always
#        links:
#            - mongo
        depends_on:
            - mongo

    account:
        image: memmojtaba/e-shopping-account_management:latest
        volumes:
            - "./.env:/account_management/.env"
        ports:
            - "5000:5000"
        restart: always
#        links:
#            - mongo_account
#            - auth
        depends_on:
            - mongo_account
            - auth
